a= input('digite um valor:')
print ('tipo da variavel:',type (a))
b= input ('digite outro valor:')
print (type (b))
print ('~~'*10)
print ('A soma entre os dois valores: {}'.format (int (a) +int (b)))
print ('A subtração entre os dois valores: {}'.format (int (a)- int (b))) 
print ('A multiplicação entre os dois valores: {}'.format (int (a) *int (b)))
print ('A divisão real e a divisão inteira ente os dois valores: {}, {}'.format (float (a) /float (b),int (a)// int (b)))
print ('A potenciação do dois valores: {}, {}'.format (int (a)**2, int (b)**2))
print ('O mod dos dois valores: {}, {}'.format (int (a)%2, int (b)%2))
print ('Tipo primitivo das variaveis {}, {}'.format (type (int (a)),type (int (b))))
input ()
