a =input ('Digite algo: ')
print ('Tipo primitivo: {}'.format (type (a)))
print ('Apens espaços: {}'.format (a.isspace()))
print ('Apenas número: {}'.format (a.isnumeric()))
print ('Apenas alfabético: {}'.format (a.isalpha()))
print ('Alfanumerico: {}'.format (a.isalnum()))
print ('Apenas maiusculo: {}'.format (a.isupper()))
print ('Apenas minsculo: {}'.format (a.islower()))
print ('Captalizada: {}'.format (a.istitle()))
input ()
