from time import sleep
print ('{}exercicio 2{}'.format ('-='*15, '-='*15))
print (' Esse program foi feito para saber a some de dois valores aleatórios;')
print ()
print ('-='*35)
print ()
a = int (input(' Digite um valor: '))
b = int (input(' Digite outro valor: '))
print ()
print (' processando...')  #quis deixar mais bonito ¯\_(ツ)_/¯
sleep (2)
print ()
print ('{}Esses são os dados;{}'.format ('-='*10, '-='*14))
print ()
print (' A some dos valores {} e {} tem como {} de resultado'.format (a, b, a+b))
print ('-='*33)
input () #coloquei esse input livre para não finalizar quando for rodar (estou usando o notepad++)