from time import sleep
print ('{}exercicio 1{}'.format ('-='*15, '-='*15))
print (' Esse programa foi feito para saber os calculos')
print ()
print ('-='*35)
print ()
a = int (input(' Digite um número inteiro: '))
b = int (input(' Digite outro número inteiro: '))
c = float (input(' Digite um número real: '))
print ()
print (' processando...')  #quis deixar mais bonito ¯\_(ツ)_/¯
sleep (2)
print ()
print ('{}Esses são os dados;{}'.format ('-='*10, '-='*14))
print ()
print (' O produto do dobro do primeiro com metade do segundo é {} '.format ((a*2)*(b/2)))
print (' A soma do triplo do primeiro com o terceiro é {}'.format ((a*3)+c))
print (' O terceiro elevado ao cubo é {}'.format (c**3))
print ('-='*33)
input () #coloquei esse input livre para não finalizar quando for rodar (estou usando o notepad++)